export const ShopCategories = [ 
    { value: "electronics", label: "Electronics" },
    { value: "fashion", label: "Fashion" },
    { value: "home_appliances", label: "Home Appliances" },
    { value: "books", label: "Books" },
    { value: "toys", label: "Toys" },
    { value: "sports", label: "Sports" },
    { value: "beauty_health", label: "Beauty & Health" },
    { value: "automotive", label: "Automotive" },
    { value: "groceries", label: "Groceries" }, 
    { value: "furniture", label: "Furniture" },
    { value: "jewelry", label: "Jewelry" },
    { value: "pet_supplies", label: "Pet Supplies" },
    { value: "stationery", label: "Stationery" },
    { value: "gardening", label: "Gardening" },
    { value: "music", label: "Music" },
    { value: "gaming", label: "Gaming" },
    { value: "health_fitness", label: "Health & Fitness" },
    { value: "baby_products", label: "Baby Products" },
    { value: "handmade", label: "Handmade" },
    { value: "art_crafts", label: "Art & Crafts" },
    { value: "collectibles", label: "Collectibles" },
    { value: "digital_products", label: "Digital Products" },
    { value: "other", label: "Other" }
]